### ISSUE TITLE
Cannot get "github" link rendered, why? 

### ISSUE THREAD

**Issue by baden32** [TYPO3-Documentation/t3docs-examples#77]
Hello,
I just installed the "examples" extension to understand how I can add my own tab to the LinkBrowser popup.
In the BE, the Github Issue Tab and field are available and I can enter an id (numeric) and I can see that I get a link defined as "github:32" in my content text.

Unfortunately in FE, the "github:32" is not rendered at all (non link in fact).

As the default project is TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, if I entered 32 is githubid, I would expect to get the github:32 rendered as https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/32.

Could you help me to get this working. What am I missing in my TS/Typo3 config?
Thank you in advance for your help,
Regards
Bads

**Comment by sypets** [comment]
@baden32 Is this an error in the examples extension? Which version are you using?

If you need support, you can also use one of several options:

* get yourself a Slack account and post your question in the channel `#typo3-cms`. 
* ask on https://talk.typo3.org/
* Alternatively, you can also ask on Stack Overflow

see https://typo3.org/help for a description of the ways to get help.

If you are completely lost, I would recommend to try to get help on slack. The other options (talk and Stack Overflow) require that you phrase your problem in a concise, very clear way, possibly with code snippets, so it is possible to find the error. On Slack you could also ask questions like, I am trying to do a or be, where can I get help?

**Comment by Hutze** [comment]
I posted a similar question in the #typo3-documentation channel some days ago, but I got no answer until today :) So I add my question here again. I also got an error with the example extension and until now I have got no idea what is missing.
I setup a blank TYPO3 v11.5.10 environment and installed “t3docs/examples”. If I click the "Github Issue" tab I get the following error:

`(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Standard->linkBrowser" in format ".html", but none of the paths contained the expected template file (Standard/LinkBrowser.html). The following paths were checked: /var/www/html/public/typo3/sysext/recordlist/Resources/Private/Templates/LinkBrowser/`

So, it is an error within the documentation and not in the core? 

I can also ask that question in the #typo3-cms channel, but I did not want to spam my problems in every channel :)

Thanks :)

**Comment by sypets** [comment]
It looks like the examples extension (and documentation) may be incomplete. Specifically, for the github linkhandler, the part for the Frontend seems to be missing. 

For the haiku linkhandler, the FE link is created. So, if you are looking for implementing a _record link handler_ (to a record in TYPO3), look at the TypoScript `Configuration/TypoScript/RecordLinks/Haiku.typoscript`

You can also look in the documenation (but as far as I have seen, the part about FE rendering for the GitHub custom link example is missing in the docs):

* https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/LinkBrowser/Linkhandler/CustomLinkHandlers.html
* https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/LinkBrowser/Linkhandler/Index.html

(I am not an expert on the examples extension, I only replied here because this was open some time.)

----

Hmm, so there are now 2 people with a problem? For me, I did not get an exception with the examples extension (in v11). The Backend part was working

For the second error with the exception, it looks like the Fluid path is not configured correctly. It is looking for a Fluid file which does not exist. This points to incorrect configuration in the extension.

Also, please make sure you

1. Added the static includes from the examples extension.You should do that in your root page:
* go to TypoScript module
* go to root page and modify template
* "Edit the whole template record
* click tab "Includes", add exmples 

![image](https://user-images.githubusercontent.com/13206455/171342854-b1561ee2-86fc-402b-8a9a-9059bfd49b3e.png)


2. Flush your cache (preferably all caches, including system cache)

As I said, I could reproduce the problem that the GitHub links were not rendered in the Frontend but I did not get the exception.

Asking in `#typo3-documentation` now ...

For support, still recommending to go to rescources listed on https://typo3.org/help

**Comment by Hutze** [comment]
@sypets Tank you very much for your quick answer. I am not sure if I have expressed it understandably, but I am getting the exception in the backend:

<img width="1334" alt="Bildschirmfoto 2022-06-01 um 10 31 27" src="https://user-images.githubusercontent.com/3949642/171362538-6556e9a3-0b8c-45c0-adab-17f6951b3a0e.png">

<img width="700" alt="Bildschirmfoto 2022-06-01 um 10 31 33" src="https://user-images.githubusercontent.com/3949642/171362561-3ec074b6-044c-4a45-bce4-4f8199572a43.png">

<img width="1093" alt="Bildschirmfoto 2022-06-01 um 10 31 57" src="https://user-images.githubusercontent.com/3949642/171362611-0e8bdaa0-36e4-42c5-a1ad-95f150af35f6.png">

I will ask for help in the #typo3-cms channel. Again: Thank you for your answer.

**Comment by runner78** [comment]
I tried to upgrade a LinkHandler I created for TYPO3 10 to 11 and got the same error message "Tried resolving a template file for controller action "Standard->linkBrowser"". I then tried examples with the same problem. I then tried the 11.5 branch, but the view is not set there, missing DI configuration?.
